### PR TITLE
Added .ruby-version

### PR DESCRIPTION
**Pull request by tlvince**
Allows `rvm` (etc.) to switch the correct Ruby version when `cd`'ing to the project root

### CODE REVIEW

**Comment by ixti** [comment]
IMHO it's better to .gitignore it rather than locking repo to specific version

**Comment by ixti** [comment]
Closed in favor of cf9cfee2bb92fbfaf18221216d11f6aadb7373d3

**Comment by tlvince** [comment]
In that case, perhaps you could take a look at the following; the reason I locked it to 1.9.3 is because in 2.0.0, I'm thrown an `<module:Sprockets>': uninitialized constant Sass::CacheStores (NameError)` ([backtrace](https://gist.github.com/6211396)).

**Comment by ixti** [comment]
Interesting indeed. It should work with ruby `2.0`. I'll try to find the reason sometime this week, meanwhile you can use `.ruby-version` locally - it will just be checked into repo, which is good solution IMHO anyway :D

**Pull request closed without merging**
